apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi  # Adjust the size as needed

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 5  # 5 replicas of Nginx
  selector:
    matchLabels:
      name: blog
  template:
    metadata:
      labels:
        name: blog
    spec:
      volumes:  # Define the volume here
      - name: html
        persistentVolumeClaim:
          claimName: html
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  replicas: 1  # Single replica of Git-Sync
  selector:
    matchLabels:
      name: git-sync
  template:
    metadata:
      labels:
        name: git-sync
    spec:
      volumes:  # Define the volume here
      - name: html
        persistentVolumeClaim:
          claimName: html
      containers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.0.1
        volumeMounts:
        - name: html
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/tejasdurge55/dice_game.git
        - name: GIT_SYNC_DEST
          value: html

---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    name: blog  # Selector for pods

    #docker kubernetes Loadbalancer command: kubectl port-forward service/blog-service 8099:80
    #then app is visible at localhost:8099

    #docker kubernetes NodePort command: kubectl port-forward service/blog-service 8099:80
    #then app is visible at localhost:8099

